import { useEffect, useMemo, useState } from "react";
import { getInquiries, updateInquiryStatus, type InquiryItem } from "../api";

const statuses = ["New", "Contacted", "Qualified", "Booked", "Closed"];

export function AdminDashboard() {
  const [token, setToken] = useState(() => window.localStorage.getItem("idesign-admin-token") || "");
  const [inquiries, setInquiries] = useState<InquiryItem[]>([]);
  const [statusFilter, setStatusFilter] = useState("All");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); const trimmed = token.trim(); if (trimmed) window.localStorage.setItem("idesign-admin-token", trimmed); try { setInquiries(await getInquiries(trimmed)); } catch { setError("Unable to load inquiries. Check the admin token and try again."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => inquiries.filter((inquiry) => statusFilter === "All" || inquiry.status === statusFilter), [inquiries, statusFilter]);
  const setStatus = async (inquiry: InquiryItem, status: string) => { const result = await updateInquiryStatus(inquiry.id, status, token.trim()); if (!result.ok || !result.inquiry) { setError(result.errors?.[0] || "Status could not be updated."); return; } setInquiries((current) => current.map((item) => item.id === inquiry.id ? result.inquiry! : item)); };
  return <div className="admin-page"><div className="admin-wrap"><header className="admin-header"><div><p>Studio Operations</p><h1>Client inquiries</h1></div><div className="admin-auth"><input type="password" value={token} onChange={(e) => setToken(e.target.value)} placeholder="Admin token" aria-label="Admin token" /><button onClick={load}>{loading ? "Loading..." : "Refresh"}</button></div></header><div className="admin-metrics">{statuses.slice(0, 4).map((status) => <div key={status}><span>{status}</span><strong>{inquiries.filter((item) => item.status === status).length}</strong></div>)}</div><div className="admin-toolbar"><span>{inquiries.length} total leads</span><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} aria-label="Filter status"><option>All</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select></div>{error && <p className="admin-error">{error}</p>}<section className="inquiry-list">{visible.map((inquiry) => { const whatsappText = encodeURIComponent(`Hi ${inquiry.fullName}, thank you for contacting iDESIGN Studio about ${inquiry.interest}. I would love to hear a little more about your project.`); return <article key={inquiry.id} className="inquiry-card"><div><p className="inquiry-date">{new Date(inquiry.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</p><h2>{inquiry.fullName}</h2><p className="inquiry-meta">{inquiry.interest} · {inquiry.timeline} · {inquiry.budget || "Budget flexible"}</p><p className="inquiry-message">{inquiry.message}</p><div className="inquiry-links"><a href={`mailto:${inquiry.email}`}>Email</a>{inquiry.phone && <a href={`https://wa.me/${inquiry.phone.replace(/\D/g, "")}?text=${whatsappText}`} target="_blank" rel="noreferrer">WhatsApp</a>}</div></div><select value={inquiry.status} onChange={(e) => setStatus(inquiry, e.target.value)} aria-label={`Set status for ${inquiry.fullName}`}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></article>; })}{!loading && visible.length === 0 && <p className="admin-empty">No inquiries match this view yet.</p>}</section></div></div>;
}
